name: Build glibc 2.27 for ARM64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          make \
          bison \
          flex \
          gettext \
          texinfo \
          xz-utils \
          zip

    - name: Download glibc source
      run: |
        wget https://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.xz
        tar xf glibc-2.27.tar.xz

    - name: Create build and install directories
      run: |
        mkdir -p glibc-build
        mkdir -p /tmp/glibc-2.27-arm64

    - name: Configure glibc
      working-directory: glibc-build
      run: |
        ../glibc-2.27/configure \
          --prefix=/ \
          --host=aarch64-linux-gnu \
          --enable-kernel=3.2.0 \
          --with-headers=/usr/aarch64-linux-gnu/include \
          --disable-multilib \
          --disable-werror

    - name: Build glibc
      working-directory: glibc-build
      run: |
        make -j$(nproc)
        make install DESTDIR=/tmp/glibc-2.27-arm64

    - name: Create zip archive
      run: |
        cd /tmp/glibc-2.27-arm64 && \
        zip -r /tmp/glibc-2.27-arm64.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: glibc-2.27-arm64
        path: /tmp/glibc-2.27-arm64.zip
