name: Build glibc 2.27 for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install basic dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make bison flex gettext texinfo xz-utils zip

      - name: Install Linaro GCC 8 toolchain
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/8.5-2021.11/aarch64-linux-gnu/gcc-linaro-8.5.0-2021.11-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf gcc-linaro-8.5.0-2021.11-x86_64_aarch64-linux-gnu.tar.xz
          echo "$PWD/gcc-linaro-8.5.0-2021.11-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_PATH

      - name: Verify compiler
        run: |
          aarch64-linux-gnu-gcc --version

      - name: Download glibc 2.27 source
        run: |
          wget https://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.xz
          tar -xf glibc-2.27.tar.xz

      - name: Configure and build
        working-directory: glibc-2.27
        run: |
          mkdir -p build && cd build
          ../configure \
            --prefix=/usr/aarch64-linux-gnu \
            --host=aarch64-linux-gnu \
            --build=x86_64-linux-gnu \
            --enable-kernel=3.2.0 \
            --with-headers=/usr/aarch64-linux-gnu/include \
            --disable-multilib \
            --disable-werror
          make -j$(nproc)
          make install DESTDIR=/tmp/glibc-install

      - name: Package artifacts
        run: |
          cd /tmp/glibc-install
          zip -r glibc-2.27-arm64.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glibc-2.27-arm64
          path: /tmp/glibc-install/glibc-2.27-arm64.zip
