name: Build glibc 2.27 for ARM64 (with ARM GCC 8)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install basic dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make bison flex gettext texinfo xz-utils zip

      - name: Download ARM GCC 8 toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/8.5-2020.12/binrel/gcc-arm-8.5-2020.12-x86_64-aarch64-linux-gnu.tar.xz
          tar -xf gcc-arm-8.5-2020.12-x86_64-aarch64-linux-gnu.tar.xz
          echo "$PWD/gcc-arm-8.5-2020.12-x86_64-aarch64-linux-gnu/bin" >> $GITHUB_PATH

      - name: Download glibc 2.27 source
        run: |
          wget https://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.xz
          tar -xf glibc-2.27.tar.xz

      - name: Configure for ARM64
        working-directory: glibc-2.27
        run: |
          mkdir -p build && cd build
          ../configure \
            --prefix=/usr/aarch64-linux-gnu \
            --host=aarch64-linux-gnu \
            --build=x86_64-linux-gnu \
            --enable-kernel=3.2.0 \
            --with-headers=/usr/aarch64-linux-gnu/include \
            --disable-multilib \
            --disable-werror

      - name: Build glibc
        working-directory: glibc-2.27/build
        run: |
          make -j$(nproc)
          make install DESTDIR=/tmp/glibc-install

      - name: Zip the compiled glibc
        run: |
          cd /tmp/glibc-install
          zip -r glibc-2.27-arm64.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glibc-2.27-arm64
          path: /tmp/glibc-install/glibc-2.27-arm64.zip
